# Generated by Django 3.2 on 2023-01-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230124_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genretitle',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genretitle',
            name='title',
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='uniqueConstraint_review',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='Рейтинг'),
        ),
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
