# Generated by Django 3.2 on 2023-01-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230119_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Модератор'), ('moderator', 'Администратор')], default='user', max_length=255, verbose_name='Роль'),
        ),
    ]
